id: P006756
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:21:15.712989
source_metadata:
  id: bdr:W8LS19198
  title: མེས་པོའི་དགོངས་རྒྱན། རྒྱུད་བཞིའི་འགྲེལ་བ་གཞན་ལ་ཕན་པའི་གཏེར།
  author: ''
  volumes:
    092a1690a0de46709e30f0aa6941bc77:
      image_group_id: I8LS19200
      title: ''
      volume_number: 1
      total_pages: 426
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
