id: IF2079AB8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T10:02:13+00:00'
last_modified: '2022-06-08T06:38:08.098269+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19198
  title: མེས་པོའི་དགོངས་རྒྱན། རྒྱུད་བཞིའི་འགྲེལ་བ་གཞན་ལ་ཕན་པའི་གཏེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BD73:
      image_group_id: I8LS19200
      title: ''
      total_pages: 426
      order: 1
      base_file: BD73.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
